security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false     
        main:    
            lazy: true
            provider: app_user_provider
            
            custom_authenticators: 
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_login

    enable_authenticator_manager: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/tasks, roles: ROLE_USER }
